openapi: 3.0.3
info:
  title: Save Management API
  version: 1.0.0
  description: API for user authentication and save file management.

servers:
  - url: https://www.temesiszabolcsistvan.hu

paths:
  /login:
    post:
      summary: Authenticate a user
      x-google-backend:
        address: https://delvelogin-978221649687.europe-north2.run.app
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [UID, Pass]
              properties:
                UID:
                  type: string
                Pass:
                  type: string
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: string
                  message:
                    type: string
        401:
          description: Unauthorized
        404:
          description: User not found

  /upload:
    post:
      summary: Upload or update a save
      x-google-backend:
        address: https://delveupload-978221649687.europe-north2.run.app
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [UID, Pass, saveName, saveData]
              properties:
                UID:
                  type: string
                Pass:
                  type: string
                saveName:
                  type: string
                saveData:
                  type: string
      responses:
        200:
          description: Save uploaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: string
                  message:
                    type: string
        500:
          description: Server error

  /saves:
    get:
      summary: List user saves
      x-google-backend:
        address: https://delvesave-978221649687.europe-north2.run.app
      parameters:
        - in: query
          name: UID
          required: true
          schema:
            type: string
        - in: query
          name: Pass
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of saves
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: string
                  saves:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        timestamp:
                          type: string
                          format: date-time

  /delete:
    delete:
      summary: Delete a specific save
      x-google-backend:
        address: https://delvedelete-978221649687.europe-north2.run.app
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [UID, Pass, saveName]
              properties:
                UID:
                  type: string
                Pass:
                  type: string
                saveName:
                  type: string
      responses:
        200:
          description: Save deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: string
                  message:
                    type: string
        404:
          description: Save not found
        401:
          description: Invalid password
